config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  root to: "restaurants#index"

  resources :restaurants
  resources :restaurants do
    resources :reviews
  end

  devise_for :users
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  validates :name,
    presence: true,
    uniqueness: true
  validates :address,
    presence: true,
    uniqueness: true
  validates :city,
    presence: true
  validates :state,
    presence: true
  validates :zipcode,
    presence: true,
    length: { is: 5 }
  validates :description,
    presence: true
  validates :category,
    inclusion: { in: %w(american indian italian thai chinese fusion mexican bbq korean mediterranean asian other),
      message: "%{value} is not a valid category." }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :rating,
    presence: true,
    numericality: { only_integer: true },
    length: { in: 1..5 }
  validates :body,
  presence: true,
  length: {
    minimum: 5,
    maximum: 250,
    tokenizer: lambda { |str| str.scan(/\w+/) },
    too_short: "A description must have at least %{count} words",
    too_long: "A description must have at most %{count} words"
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.order('id DESC').limit('10')
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = "Success!"
      redirect_to '/restaurants'
    else
      flash.now[:notice] = "Your restaurant couldn't be saved."
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zipcode, :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant_id = @restaurant.id
    if @review.save
      flash[:notice] = "Success!"
      redirect_to "/restaurants"
    else
      flash.now[:notice] = "Your review couldn't be saved."
      render '/restaurants/:restaurant_id/reviews/new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h3>Restaurant List</h3>

<div>
  <ul>
    <% @restaurants.each do |restaurant| %>
      <li><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></li>
    <% end %>
  </ul>
</div>

<div>
  <%= link_to "New Restaurant", new_restaurant_path(@restaurant) %>
</div>

app/views/restaurants/new.html.erb
<h3>Add a Restaurant</h3>

<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

   <div>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>

app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>
<%= @restaurant.category %>

<div>
  <h4> Address: </h4>
  <%= @restaurant.address %><br>
  <%= "#{@restaurant.city}, #{@restaurant.state} #{@restaurant.zipcode}"  %>
</div>

<h4> Description </h4>
<div>
  <%= @restaurant.description %>
</div>

<br>

<div>
  <h4> Reviews </h4>
  <table style="width:300px">
    <tr>
      <th>Rating</th>
      <th>Description</th>
      <th>Posted At</th>
    </tr>
    <tr>
      <% @restaurant.reviews.each do |review| %>
        <td><%= review.rating %></td>
        <td><%= review.body %></td>
        <td><%= review.created_at %></td>
      <% end %>
    </tr>
  </table>
</div>
<%= link_to 'Create a Review', new_restaurant_review_path(@restaurant) %>
<!-- How do I create a link with the correct path to new review here? -->
<br>
<%= link_to "Back to Restaurants", restaurants_path(@restaurants) %>

app/views/reviews/new.html.erb
<h3>Add a Review</h3>

<%= form_for [@restaurant, @review] do |f| %>

  <% if @review.errors.any? %>
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>